
x-db-conf: &db-conf
  POSTGRES_DB: python_db
  POSTGRES_PASSWORD: $DB_PASSWORD
  POSTGRES_USER: python

services:
  postgres:
    environment: *db-conf
    image: postgres:14-alpine
    ports: 
      - 5432:5432
    volumes: 
      - local_pgdata:/var/lib/postgresql/data

  python:
    build: 
      context: ./python
      dockerfile: dockerfile
    environment: *db-conf
    ports:
      - 8000:8000
    volumes:
      - ./python:/app
    
  web:
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./web:/app

volumes:
  local_pgdata: