FROM python:3.9

WORKDIR /app

COPY ./requirements.txt /app/

RUN \
  apt-get update &&\
  apt-get install python3-psycopg2 &&\
  pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./* /app/

CMD ["fastapi", "dev", "main.py", "--port", "8000", "--host", "0.0.0.0"]